version: '3'
services:
  app:
    build: ./build
    ports: 
      - '8080:8080'
    networks: 
      - test
    links:
      - 'redis:redis'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always
    networks:
      - test
networks:
  test:
 
